//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwShRNGLibrary.EncounterData.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwShRNGLibrary.EncounterData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [
        ///  { &quot;mapName&quot;: &quot;2番道路&quot;, &quot;basicLv&quot;: 4, &quot;variableLv&quot;: 3, &quot;table&quot;: { &quot;rate&quot;: [ 80, 15, 5 ], &quot;content&quot;: [ &quot;コイキング&quot;, &quot;カムカメ&quot;, &quot;サシカマス&quot; ] } },
        ///  { &quot;mapName&quot;: &quot;2番道路(湖の奥)&quot;, &quot;basicLv&quot;: 37, &quot;variableLv&quot;: 4, &quot;table&quot;: { &quot;rate&quot;: [ 50, 40, 9, 1 ], &quot;content&quot;: [ &quot;コイキング&quot;, &quot;カムカメ&quot;, &quot;コイキング&quot;, &quot;ヒンバス&quot; ] } },
        ///  { &quot;mapName&quot;: &quot;4番道路&quot;, &quot;basicLv&quot;: 13, &quot;variableLv&quot;: 3, &quot;table&quot;: { &quot;rate&quot;: [ 70, 20, 10 ], &quot;content&quot;: [ &quot;コイキング&quot;, &quot;カムカメ&quot;, &quot;トサキント&quot; ] } },
        ///  { &quot;mapName&quot;: &quot;5番道路&quot;, &quot;basicLv&quot;: 16, &quot;variableLv&quot;: 3, &quot;table&quot;: { &quot;rate&quot;: [ 70, 20, 10 ] [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fishing_sh {
            get {
                return ResourceManager.GetString("Fishing_sh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  { &quot;mapName&quot;: &quot;2番道路&quot;, &quot;basicLv&quot;: 4, &quot;variableLv&quot;: 3, &quot;table&quot;: { &quot;rate&quot;: [ 80, 15, 5 ], &quot;content&quot;: [ &quot;コイキング&quot;, &quot;カムカメ&quot;, &quot;サシカマス&quot; ] } },
        ///  { &quot;mapName&quot;: &quot;2番道路(湖の奥)&quot;, &quot;basicLv&quot;: 37, &quot;variableLv&quot;: 4, &quot;table&quot;: { &quot;rate&quot;: [ 50, 40, 9, 1 ], &quot;content&quot;: [ &quot;コイキング&quot;, &quot;カムカメ&quot;, &quot;コイキング&quot;, &quot;ヒンバス&quot; ] } },
        ///  { &quot;mapName&quot;: &quot;4番道路&quot;, &quot;basicLv&quot;: 13, &quot;variableLv&quot;: 3, &quot;table&quot;: { &quot;rate&quot;: [ 70, 20, 10 ], &quot;content&quot;: [ &quot;コイキング&quot;, &quot;カムカメ&quot;, &quot;トサキント&quot; ] } },
        ///  { &quot;mapName&quot;: &quot;5番道路&quot;, &quot;basicLv&quot;: 16, &quot;variableLv&quot;: 3, &quot;table&quot;: { &quot;rate&quot;: [ 70, 20, 10 ] [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fishing_sw {
            get {
                return ResourceManager.GetString("Fishing_sw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;, &quot;basicLv&quot;: 2, &quot;variableLv&quot;: 4, &quot;table&quot;: { &quot;rate&quot;: [40,30,15,10,5], &quot;content&quot;: [&quot;ホシガリス&quot;,&quot;サッチムシ&quot;,&quot;キャタピー&quot;,&quot;アゴジムシ&quot;,&quot;ホーホー&quot;] }, &quot;weather&quot;: 0 },
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;, &quot;basicLv&quot;: 2, &quot;variableLv&quot;: 4, &quot;table&quot;: { &quot;rate&quot;: [40,30,15,10,5], &quot;content&quot;: [&quot;ホシガリス&quot;,&quot;サッチムシ&quot;,&quot;キャタピー&quot;,&quot;アゴジムシ&quot;,&quot;ホーホー&quot;] }, &quot;weather&quot;: 1 },
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;, &quot;basicLv&quot;: 2, &quot;variableLv&quot;: 4, &quot;table&quot;: { &quot;rate&quot;: [40,30,15,10,5], &quot;content&quot;: [&quot;ホシガリス&quot;,&quot;サッチムシ&quot;,&quot;キャタピー&quot;,&quot;アゴジムシ&quot;,&quot;ホーホー&quot;] }, &quot;weather&quot;: 2 },
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;,  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hidden_sh {
            get {
                return ResourceManager.GetString("Hidden_sh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;, &quot;basicLv&quot;: 2, &quot;variableLv&quot;: 4, &quot;table&quot;: { &quot;rate&quot;: [40,30,15,10,5], &quot;content&quot;: [&quot;ホシガリス&quot;,&quot;サッチムシ&quot;,&quot;キャタピー&quot;,&quot;アゴジムシ&quot;,&quot;ホーホー&quot;] }, &quot;weather&quot;: 0 },
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;, &quot;basicLv&quot;: 2, &quot;variableLv&quot;: 4, &quot;table&quot;: { &quot;rate&quot;: [40,30,15,10,5], &quot;content&quot;: [&quot;ホシガリス&quot;,&quot;サッチムシ&quot;,&quot;キャタピー&quot;,&quot;アゴジムシ&quot;,&quot;ホーホー&quot;] }, &quot;weather&quot;: 1 },
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;, &quot;basicLv&quot;: 2, &quot;variableLv&quot;: 4, &quot;table&quot;: { &quot;rate&quot;: [40,30,15,10,5], &quot;content&quot;: [&quot;ホシガリス&quot;,&quot;サッチムシ&quot;,&quot;キャタピー&quot;,&quot;アゴジムシ&quot;,&quot;ホーホー&quot;] }, &quot;weather&quot;: 2 },
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;,  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hidden_sw {
            get {
                return ResourceManager.GetString("Hidden_sw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  { &quot;mapName&quot;: &quot;2番道路&quot;, &quot;name&quot;: &quot;カムカメ&quot;, &quot;lv&quot;: 8 },
        ///  { &quot;mapName&quot;: &quot;2番道路&quot;, &quot;name&quot;: &quot;カジリガメ&quot;, &quot;lv&quot;: 50, &quot;flawlessIVs&quot;: 3 },
        ///  { &quot;mapName&quot;: &quot;2番道路&quot;, &quot;name&quot;: &quot;ラプラス&quot;, &quot;lv&quot;: 55, &quot;flawlessIVs&quot;: 3 },
        ///  { &quot;mapName&quot;: &quot;2番道路&quot;, &quot;name&quot;: &quot;タチフサグマ&quot;, &quot;lv&quot;: 50 },
        ///  { &quot;mapName&quot;: &quot;2番道路&quot;, &quot;name&quot;: &quot;ワンパチ&quot;, &quot;lv&quot;: 8 },
        ///  { &quot;mapName&quot;: &quot;5番道路&quot;, &quot;name&quot;: &quot;ワタシラガ&quot;, &quot;lv&quot;: 22 },
        ///  { &quot;mapName&quot;: &quot;8番道路&quot;, &quot;name&quot;: &quot;イワパレス&quot;, &quot;lv&quot;: 40 },
        ///  { &quot;mapName&quot;: &quot;9番道路&quot;, &quot;name&quot;: &quot;オニゴーリ&quot;, &quot;lv&quot;: 55, &quot;flawlessIVs&quot;: 3 },
        ///  { &quot;mapName&quot;: &quot;ターフタウン&quot;, &quot;name&quot;: &quot;シ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Limited_sh {
            get {
                return ResourceManager.GetString("Limited_sh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  { &quot;mapName&quot;: &quot;2番道路&quot;, &quot;name&quot;: &quot;カムカメ&quot;, &quot;lv&quot;: 8 },
        ///  { &quot;mapName&quot;: &quot;2番道路&quot;, &quot;name&quot;: &quot;カジリガメ&quot;, &quot;lv&quot;: 50, &quot;flawlessIVs&quot;: 3 },
        ///  { &quot;mapName&quot;: &quot;2番道路&quot;, &quot;name&quot;: &quot;ラプラス&quot;, &quot;lv&quot;: 55, &quot;flawlessIVs&quot;: 3 },
        ///  { &quot;mapName&quot;: &quot;2番道路&quot;, &quot;name&quot;: &quot;タチフサグマ&quot;, &quot;lv&quot;: 50 },
        ///  { &quot;mapName&quot;: &quot;2番道路&quot;, &quot;name&quot;: &quot;ワンパチ&quot;, &quot;lv&quot;: 8 },
        ///  { &quot;mapName&quot;: &quot;5番道路&quot;, &quot;name&quot;: &quot;ワタシラガ&quot;, &quot;lv&quot;: 22 },
        ///  { &quot;mapName&quot;: &quot;8番道路&quot;, &quot;name&quot;: &quot;イワパレス&quot;, &quot;lv&quot;: 40 },
        ///  { &quot;mapName&quot;: &quot;9番道路&quot;, &quot;name&quot;: &quot;オニゴーリ&quot;, &quot;lv&quot;: 55, &quot;flawlessIVs&quot;: 3 },
        ///  { &quot;mapName&quot;: &quot;ターフタウン&quot;, &quot;name&quot;: &quot;シ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Limited_sw {
            get {
                return ResourceManager.GetString("Limited_sw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  { &quot;mapName&quot;: &quot;3番道路&quot;, &quot;weather&quot;: 0, &quot;name&quot;: &quot;アオガラス&quot;, &quot;lv&quot;: 18, &quot;shinyLocked&quot;: true },
        ///  { &quot;mapName&quot;: &quot;4番道路&quot;, &quot;weather&quot;: 0, &quot;name&quot;: &quot;ディグダ&quot;, &quot;lv&quot;: 17 },
        ///  { &quot;mapName&quot;: &quot;8番道路&quot;, &quot;weather&quot;: 0, &quot;name&quot;: &quot;タイレーツ&quot;, &quot;lv&quot;: 40 },
        ///  { &quot;mapName&quot;: &quot;9番道路&quot;, &quot;weather&quot;: 4, &quot;name&quot;: &quot;オトスパス&quot;, &quot;lv&quot;: 50 },
        ///  { &quot;mapName&quot;: &quot;10番道路&quot;, &quot;weather&quot;: 5, &quot;name&quot;: &quot;ユキノオー&quot;, &quot;lv&quot;: 55 },
        ///  { &quot;mapName&quot;: &quot;10番道路&quot;, &quot;weather&quot;: 5, &quot;name&quot;: &quot;ツンベアー&quot;, &quot;lv&quot;: 55 },
        ///  { &quot;mapName&quot;: &quot;ガラル鉱山&quot;, &quot;weather&quot;: 0, &quot;name&quot;: &quot;トロッゴン&quot;, &quot;lv&quot;: 18 },
        ///  { &quot;mapName&quot;: &quot;ガ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Static_sh {
            get {
                return ResourceManager.GetString("Static_sh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  { &quot;mapName&quot;: &quot;3番道路&quot;, &quot;weather&quot;: 0, &quot;name&quot;: &quot;アオガラス&quot;, &quot;lv&quot;: 18, &quot;shinyLocked&quot;: true },
        ///  { &quot;mapName&quot;: &quot;4番道路&quot;, &quot;weather&quot;: 0, &quot;name&quot;: &quot;ディグダ&quot;, &quot;lv&quot;: 17 },
        ///  { &quot;mapName&quot;: &quot;5番道路&quot;, &quot;weather&quot;: 0, &quot;name&quot;: &quot;ワタシラガ&quot;, &quot;lv&quot;: 22 },
        ///  { &quot;mapName&quot;: &quot;8番道路&quot;, &quot;weather&quot;: 0, &quot;name&quot;: &quot;タイレーツ&quot;, &quot;lv&quot;: 40 },
        ///  { &quot;mapName&quot;: &quot;9番道路&quot;, &quot;weather&quot;: 4, &quot;name&quot;: &quot;オトスパス&quot;, &quot;lv&quot;: 50 },
        ///  { &quot;mapName&quot;: &quot;10番道路&quot;, &quot;weather&quot;: 5, &quot;name&quot;: &quot;ユキノオー&quot;, &quot;lv&quot;: 55 },
        ///  { &quot;mapName&quot;: &quot;10番道路&quot;, &quot;weather&quot;: 5, &quot;name&quot;: &quot;ツンベアー&quot;, &quot;lv&quot;: 55 },
        ///  { &quot;mapName&quot;: &quot;ガラ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Static_sw {
            get {
                return ResourceManager.GetString("Static_sw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;, &quot;basicLv&quot;: 3, &quot;variableLv&quot;: 4, &quot;table&quot;: { &quot;rate&quot;: [50,30,15,5], &quot;content&quot;: [&quot;ホシガリス&quot;,&quot;ココガラ&quot;,&quot;ウールー&quot;,&quot;クスネ&quot;] }, &quot;weather&quot;: 0 },
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;, &quot;basicLv&quot;: 3, &quot;variableLv&quot;: 4, &quot;table&quot;: { &quot;rate&quot;: [50,30,15,5], &quot;content&quot;: [&quot;ホシガリス&quot;,&quot;ココガラ&quot;,&quot;ウールー&quot;,&quot;クスネ&quot;] }, &quot;weather&quot;: 1 },
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;, &quot;basicLv&quot;: 3, &quot;variableLv&quot;: 4, &quot;table&quot;: { &quot;rate&quot;: [50,30,15,5], &quot;content&quot;: [&quot;ホシガリス&quot;,&quot;ココガラ&quot;,&quot;ウールー&quot;,&quot;クスネ&quot;] }, &quot;weather&quot;: 2 },
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;, &quot;basicLv&quot;: 3, &quot;variableLv&quot;: 4, &quot;table&quot;: {  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Symbol_sh {
            get {
                return ResourceManager.GetString("Symbol_sh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;, &quot;basicLv&quot;: 3, &quot;variableLv&quot;: 4, &quot;table&quot;: { &quot;rate&quot;: [50,30,15,5], &quot;content&quot;: [&quot;ホシガリス&quot;,&quot;ココガラ&quot;,&quot;ウールー&quot;,&quot;クスネ&quot;] }, &quot;weather&quot;: 0 },
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;, &quot;basicLv&quot;: 3, &quot;variableLv&quot;: 4, &quot;table&quot;: { &quot;rate&quot;: [50,30,15,5], &quot;content&quot;: [&quot;ホシガリス&quot;,&quot;ココガラ&quot;,&quot;ウールー&quot;,&quot;クスネ&quot;] }, &quot;weather&quot;: 1 },
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;, &quot;basicLv&quot;: 3, &quot;variableLv&quot;: 4, &quot;table&quot;: { &quot;rate&quot;: [50,30,15,5], &quot;content&quot;: [&quot;ホシガリス&quot;,&quot;ココガラ&quot;,&quot;ウールー&quot;,&quot;クスネ&quot;] }, &quot;weather&quot;: 2 },
        ///  { &quot;mapName&quot;: &quot;1番道路&quot;, &quot;basicLv&quot;: 3, &quot;variableLv&quot;: 4, &quot;table&quot;: {  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Symbol_sw {
            get {
                return ResourceManager.GetString("Symbol_sw", resourceCulture);
            }
        }
    }
}
