//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwShRNGLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwShRNGLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   あくしゅう,Stench
        ///あめふらし,Drizzle
        ///かそく,Speed Boost
        ///カブトアーマー,Battle Armor
        ///がんじょう,Sturdy
        ///しめりけ,Damp
        ///じゅうなん,Limber
        ///すながくれ,Sand Veil
        ///せいでんき,Static
        ///ちくでん,Volt Absorb
        ///ちょすい,Water Absorb
        ///どんかん,Oblivious
        ///ノーてんき,Cloud Nine
        ///ふくがん,Compound Eyes
        ///ふみん,Insomnia
        ///へんしょく,Color Change
        ///めんえき,Immunity
        ///もらいび,Flash Fire
        ///りんぷん,Shield Dust
        ///マイペース,Own Tempo
        ///きゅうばん,Suction Cups
        ///いかく,Intimidate
        ///かげふみ,Shadow Tag
        ///さめはだ,Rough Skin
        ///ふしぎなまもり,Wonder Guard
        ///ふゆう,Levitate
        ///ほうし,Effect Spore
        ///シンクロ,Synchronize
        ///クリアボディ,Clear Body
        ///しぜんかいふく,Natural Cure        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ability_eng {
            get {
                return ResourceManager.GetString("Ability_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   うららか草原,Rolling Fields
        ///こもれび林,Dappled Grove
        ///見張り塔跡地,Watchtower Ruins
        ///キバ湖・西,West Lake Axewell
        ///キバ湖・東,East Lake Axewell
        ///キバ湖の瞳,Axew&apos;s Eye
        ///ミロカロ湖・南,South Lake Miloch
        ///ミロカロ湖・北,North Lake Miloch
        ///巨人の腰かけ,Giant&apos;s Seat
        ///エンジンリバーサイド,Motostoke Riverbank
        ///ハシノマ原っぱ,Bridge Field
        ///ストーンズ原野,Stony Wilderness
        ///砂塵の窪地,Dusty Bowl
        ///巨人の帽子,Giant&apos;s Cap
        ///巨人の鏡池,Giant&apos;s Mirror
        ///ナックル丘陵,Hammerlocke Hills
        ///げきりんの湖,Lake of Outrage
        ///イベント,Event
        ///一礼野原,Fields of Honor
        ///清涼湿原,Soothing Wetlands
        ///集中の森,Forest of Focus
        ///チャレンジビーチ,Challenge Beach
        ///ファイトケ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MapName_eng {
            get {
                return ResourceManager.GetString("MapName_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フシギダネ,Bulbasaur
        ///フシギソウ,Ivysaur
        ///フシギバナ,Venusaur
        ///ヒトカゲ,Charmander
        ///リザード,Charmeleon
        ///リザードン,Charizard
        ///ゼニガメ,Squirtle
        ///カメール,Wartortle
        ///カメックス,Blastoise
        ///キャタピー,Caterpie
        ///トランセル,Metapod
        ///バタフリー,Butterfree
        ///ビードル,Weedle
        ///コクーン,Kakuna
        ///スピアー,Beedrill
        ///ポッポ,Pidgey
        ///ピジョン,Pidgeotto
        ///ピジョット,Pidgeot
        ///コラッタ,Rattata
        ///ラッタ,Raticate
        ///オニスズメ,Spearow
        ///オニドリル,Fearow
        ///アーボ,Ekans
        ///アーボック,Arbok
        ///ピカチュウ,Pikachu
        ///ライチュウ,Raichu
        ///サンド,Sandshrew
        ///サンドパン,Sandslash
        ///ニドラン♀,Nidoran♀
        ///ニドリーナ,Nidorina
        ///ニドクイン,Nidoqueen
        ///ニドラン♂,Nidoran♂
        ///ニドリーノ,Nidorino
        ///ニドキング,Nid [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PokeName_eng {
            get {
                return ResourceManager.GetString("PokeName_eng", resourceCulture);
            }
        }
    }
}
